# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92b3ecb0774c3f70c4132ba133ee57a5af459c4f642971f6911fd0a9b14644fb723890ffe0e9903e64fba9f4fd24b6f67aaf9ff545164e5b420843836e174d1e

test:
  secret_key_base: 250250ba7d4b7359facf48b6be0552697953e5365bfecb3d3847d0c09a685adf7e11bbd5e900d843a925531e33424e99b07d4f3e5f49f9eb07fcf8771e997aae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
